#!/bin/bash

# The xxx_START_COMMAND variables can be empty.

LOCAL_AWAVE_DIRECTORY="/home/sdx/dev"
CONTAINER_AWAVE_DIRECTORY="/development"
MANIFEST_FILE="/development/configuration/sense-testing/twoswitch-onelc-noncorsa.manifest"
PYTHON_PATH=".:/development/"
SOX_DOCKER_NETWORK="sox-sdx-net"


SDX_CONTAINER_NAME="sox_sdx_controller"
SDX_VOLUMES="$LOCAL_AWAVE_DIRECTORY:$CONTAINER_AWAVE_DIRECTORY:rw"
SDX_IPADDR="0.0.0.0"
#SDX_IPADDR=10.0.2.15
#SDX_EXTERNAL_IP="127.0.0.1"
SDX_EXTERNAL_PORT=5000
SDX_SENSE_PORT=5001
SDX_LC_IP="127.0.0.1"
SDX_LC_PORT=5555
SDX_START_COMMAND=""

SENSE_CONTAINER_NAME="stackv"
SENSE_PORT_ONE=8443
SENSE_PORT_TWO=9993
SENSE_KC_SERVER=SENSITIVE
