# Copright 2016 - Sean Donovan
# AtlantiWave/SDX Project

''' This file contains constants that are used by more than one module. 
    Example usage: defining the addresses that are used for communication
    between different components. '''

# Define time format in use with handling rules.
rfc3339format = "%Y-%m-%dT%H:%M:%S"
MAXENDTIME = "2100-01-01T00:00:00"

# Username for automatically generated rules
AUTOGENERATED_USERNAME = "SDXCTLR"


